-- FIND THE TOTAL NUMBER OF RECORDS IN THE PRODUCT TABLE 
SELECT COUNT(*) AS CNT
FROM orders.product;

-- [2.1] FETCH SUM OF PRODUCTS PRICE AND AVERAGE PRODUCT PRICE FOR EACH PRODUCT_CLASS_CODE
-- [2.2] SELECT ONLY THE PRODUCT CLASSES THAT HAVE AN AVARAGE PRICE >= 4000
SELECT PRODUCT_CLASS_CODE, SUM(PRODUCT_PRICE) AS TOTAL_PRICE, AVG(PRODUCT_PRICE) AS AVG_PRICE
FROM orders.product
GROUP BY PRODUCT_CLASS_CODE 
HAVING AVG_PRICE >= 4000;

-- [3] FETCH TOTAL NUMBER OF MALE AND FEMALE CUSTOMERS ; (USE ONLINE_CUSTOMER TABLE)
SELECT CUSTOMER_GENDER, COUNT(CUSTOMER_GENDER) AS GENDER_COUNT
FROM orders.online_customer
GROUP BY CUSTOMER_GENDER;

-- [4] DISPLAY THE COUNT OF UNIQUE CITIES IN THE ADDRESS TABLE 
SELECT COUNT(DISTINCT CITY) AS UNIQUE_CITY
FROM orders.address;

/* [5] CHECK YOUR INVENTORY STOCK:
   IF QUANTITY IS LESS THAN 50 AND LESS THAN OR EQUAL TO 150, CALL IT "MEDUM STOCK"
   IF QUANTITY IS GREATER THAN 150, "HIGH STOCK" */
SELECT PRODUCT_ID, PRODUCT_DESC, PRODUCT_CLASS_CODE, PRODUCT_QUANTITY_AVAIL, 
CASE 
	WHEN PRODUCT_QUANTITY_AVAIL <= 50 THEN "Low stock"
    WHEN PRODUCT_QUANTITY_AVAIL > 50 and PRODUCT_QUANTITY_AVAIL <= 150 THEN "Medium stock"
	WHEN PRODUCT_QUANTITY_AVAIL > 150 THEN "High stock"
END AS AVAILABILITY_STATUS
FROM orders.product;