-- [1] DISPLAY ETIRE DATA FROM PRODUCTS TABLE
SELECT *
FROM orders.product;

-- [2] DISPLAY ONLY ADDRESS_ID, CITY, STATE, AND PINCODE COLUMNS FROM ADDRESS TABLE
 SELECT ADDRESS_ID,CITY, STATE, PINCODE
 FROM orders.address;
 
-- [3] DISPLAY UNIQUE CITIES IN TEH ADDRESS TABLE 
SELECT distinct CITY
FROM orders.address;

-- [4] DISPLAY ALL THE RECORDS FROM PRODUCTS TABLE WHOSE PRODUCT_ID IS 99999
DELETE 	
FROM orders.product
WHERE PRODUCT_ID = 99999;

-- Deleting will not display it so to take a look at what it looks like:
SELECT *
FROM orders.product;

-- [5] UPDATE THE PRICE OF ALL PRODUCTS IN THE PRODUCTS TABLE TO A 25% LESSER VALUE 
SET SQL_SAFE_UPDATES = 0; -- To eliminate the error 
UPDATE orders.product
SET PRODUCT_PRICE = PRODUCT_PRICE - (PRODUCT_PRICE * 0.25);
SELECT *
FROM orders.product;

-- [6] DISPLAY THE TOP 10 ROWS FROM ADDRESS TABLE
SELECT * 
FROM orders.address
LIMIT 10;