-- [1] DISPLAY ALL THE RECORDS FROM ADDRESS TABLE WHERE STATE = 'NYY'
SELECT *
FROM orders.address
WHERE STATE = 'NY';
-- [2] FETCH THE RECORDS FROM THE ADDRESS TABLE FOR NY, CT AND AL STATES
SELECT *
FROM orders.address
WHERE STATE IN ('NY', 'CT', 'AL');
-- [3] FETCH THE RECORDS FROM  THE ADDRESS TABLE WHERE STATE IS NOT TULL 
SELECT *
FROM orders.address
WHERE STATE IS NOT NULL;
-- [4] FETCH THE RECORDS FROM ADDRESS TABLE WHERE CITY NAME STARTS WITH THE LETTER 'B' 
-- B% MEANS THAT LETTER B WILL BE FOLLOWED BY ANY NUMBER OF CHARATERS 
SELECT *
FROM orders.address
WHERE CITY LIKE 'B%';
-- [5] FETCH THE RECORDS FROM ADDRESS TABLE WHERE CITY NAME CONTAINS EXACTLY 5 LETTERS 
-- _ IS TO MATCH ANY SINGLE CHARACTER. FOR EXAMPLE - TO MATCH 3 CHARACTERS THREE UNDERSCORES (_) WILL BE SPECIFIED. 
SELECT *
FROM orders.address
WHERE CITY LIKE '_____';
-- [6] FETACH ALL THE RECORDS FROM THE PRODUCTS TABLE WHOSE PRODUCT_PRICE IS BETWEEN 500 AND 10000 
SELECT *
FROM orders.product
WHERE PRODUCT_PRICE BETWEEN 5000 AND 10000; -- In the previous vid we updated the prices so keep version control in mind* ?
-- [7] FETCH ALL THE RECORDS FROM PRODUCTS TABLE WHERE PRODUCT PRICE IS LESS THAN 1000 AND QUANTITY AVAILABLE IS MORE THAN 100
SELECT *
FROM orders.product
WHERE PRODUCT_PRICE < 1000 AND PRODUCT_QUANTITY_AVAIL > 100;
-- [8] FETCH ALL THE RECORDS FROM PRODUCTS TABLE WHERE PRODUCT PRICE IS LESS THAN 100 OR QUANTITY AVAILABLE IS LESS THAN 50
SELECT *
FROM orders.product
WHERE PRODUCT_PRICE < 1000 OR PRODUCT_QUANTITY_AVAIL < 50;