-- [1] FETCH ALL THE PRODUCTS WHICH FALL UNDER ELECTRONICS CATEGORY; (USE PRODUCT & PRODUCT_CLASS CATEGORY)
-- UPPER() CONVERTS THE NAMES OF ALL PRODUCT_CLASS_DESCRIPTION TO UPPER CASE and LOWER() TO LOWER CASE.
SELECT * 
FROM orders.product AS PR
	INNER JOIN orders.product_class AS PC
    ON PC.PRODUCT_CLASS_CODE = PR.PRODUCT_CLASS_CODE 
WHERE UPPER(PRODUCT_CLASS_DESC) = 'ELECTRONICS';

-- [2] QUERY CUSTOMER_ID, CUSTOMER FULL NAME, ORDER_ID, PRODUCT_QUANTITY OF CUSTOMERS WHO BOUGHT MORE THAN 10 ITEMS
-- (USE TABLES ONLINE_CUSTOMER, ORDER_HEADER, ORDER_ITEMS)
SELECT 
	OC.CUSTOMER_ID,
    CONCAT(OC.CUSTOMER_FNAME, ' ', OC.CUSTOMER_LNAME) AS FULL_NAME,
    OH.ORDER_ID, 
    SUM(OI.PRODUCT_QUANTITY) AS TOTAL_PURCHASE_QUANTITY
FROM orders.online_customer AS OC
	INNER JOIN orders.order_header AS OH 
		ON OC.CUSTOMER_ID = OH.CUSTOMER_ID
	INNER JOIN orders.order_items AS OI
		ON OH.ORDER_ID = OI.ORDER_ID
GROUP BY
	OC.CUSTOMER_ID,
    FULL_NAME,
    OH.ORDER_ID
HAVING TOTAL_PURCHASE_QUANTITY >10;

-- [3] FETCH ALL THE PRODUCTS WHICH HAVE NOT BEEN ORDERED YET
SELECT
	PRODUCT_ID,	
    PRODUCT_DESC, 
    PRODUCT_PRICE, 
    OI.PRODUCT_QUANTITY
FROM orders.product
	LEFT JOIN orders.order_items AS OI USING(PRODUCT_ID) -- THIS IS THE SAME AS SAYING X.A = Y.B
WHERE OI.PRODUCT_QUANTITY IS NULL;
-- [4] WRITE A QUERY TO FETCH ALL THE PRODUCT CATEGORY DESCRIPTIONS WHOSE AVERAGE PRICE IS > 5000
SELECT 
	PR.PRODUCT_CLASS_CODE, 
	PC.PRODUCT_CLASS_DESC,
	AVG(PRODUCT_PRICE) AS AVERAGE_PRODUCT_PRICE 
FROM orders.product AS PR
INNER JOIN orders.product_class AS PC USING(PRODUCT_CLASS_CODE)
GROUP BY PRODUCT_CLASS_CODE
HAVING AVERAGE_PRODUCT_PRICE > 5000;


-- [5] WRITE A QUERY TO GET ALL THE COLUMNS AND ROWS FROM BOTH ORDER_HEADER AND ORDER_ITEMS
-- MySQL DOES NOT SUPPORT FULL OUTER JOIN DIRECTLY INSTED IT IS DONE BY USING THE UNION CLAUSE
SELECT * FROM orders.order_header AS OH
LEFT JOIN orders.order_items ON OH.ORDER_ID = ORDER_ITEMS.ORDER_ID
UNION
SELECT * FROM orders.order_header as OH 
RIGHT JOIN orders.order_items ON OH.ORDER_ID = ORDER_ITEMS.ORDER_ID;